<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '9,13',
    'catname' => '关于中博',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'aboutus',
    'url' => 'http://zb.php.xmfeel.com/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'guanyuzhongbo',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '业务体系',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'business',
    'url' => 'http://zb.php.xmfeel.com/index.php?m=content&c=index&a=lists&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yewutixi',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '新闻中心',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'news',
    'url' => 'http://zb.php.xmfeel.com/index.php?m=content&c=index&a=lists&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xinwenzhongxin',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '社会责任',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'responsibility',
    'url' => 'http://zb.php.xmfeel.com/index.php?m=content&c=index&a=lists&catid=12',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shehuizeren',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '9',
    'arrparentid' => '0,9',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '企业简介',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '/',
    'catdir' => 'introduction',
    'url' => 'http://zb.php.xmfeel.com/index.php?m=content&c=index&a=lists&catid=13',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"default","page_template":"page","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'qiyejianjie',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
);
?>